### PR TITLE
👷 Generate issue with image

### PR DESCRIPTION
**Pull request by nikhilbadyal**

### CODE REVIEW

**Comment by IMXEren** [comment]
If the script any how breaks, add a fallback css selector for the icon - `"div.qxNhq > img"`.

**Comment by nikhilbadyal** [comment]
> If the script any how breaks, add a fallback css selector for the icon - `"div.qxNhq > img"`.

We have a fallback already if unable to get url.(Default Android Icon). 

I'll check what's inside this div. If it's another way to get an icon I'll add it.

**Comment by nikhilbadyal** [comment]
I don't find this `"div.qxNhq > img"`. Do you have any example Gplay link where this div contains app icon.

**Comment by IMXEren** [comment]
https://play.google.com/store/apps/details?id=com.google.android.youtube

**Comment by nikhilbadyal** [comment]
I think I should use `<script>` tag instead of making guess on [divs](https://github.com/nikhilbadyal/docker-py-revanced/commit/b8c8983de8e77f4a428c8e28226fc3ea906c0713).

**Pull request merged**
