### PR TITLE
✨ Scraper improvements

### PR DESCRIPTION
**Pull request by IMXEren**
- **APKPure**: 
    - ~~fix mapping from source dl~~
    - specific versions and bundle patch support
- **APKMonk**: fix extraction of dl
- **APKSOS**: add bundle patch support

### CODE REVIEW

**Comment by nikhilbadyal** [comment]
Hey @IMXEren , thanks for the PR. Just a question is the PR ready? If yes, can you rix the linter. I can review it then.

**Comment by IMXEren** [comment]
Yes, this seems good. You may proceed...

CC: @nikhilbadyal

**Comment by nikhilbadyal** [comment]
LGTM.

**Review by nikhilbadyal — APPROVED** [review]

**Comment by IMXEren** [comment]
Hey @nikhilbadyal , so I forgot editing [`README`](https://github.com/nikhilbadyal/docker-py-revanced/blob/9f8a7cc836113e3d6b652eab228c8642e779b66b/README.md?plain=1#L237):

> APKPURE - Supports downloading only latest version 
> \# Supports downloading any available version

I suppose you can do that.

**Pull request merged**
