### PR TITLE
Handle Invalid Characters in file names

### PR DESCRIPTION
**Pull request by IMXEren**
This is proposed in response to erroring out while uploading apks when file name contain invalid characters.

[Reference](https://github.com/IMXEren/rvx-builds/actions/runs/5534143308/jobs/10098697234); errors

[Test](https://github.com/IMXEren/rvx-builds/actions/runs/5534336276/jobs/10099153028); works!

### CODE REVIEW

**Comment by Spacellary** [comment]
👍

**Comment by nikhilbadyal** [comment]
Currently we don't download or create file with such naming convention. I indeed see the issue in file name **reddit_sync-vv23.05.03-17:18-output.apk** in your fork. Is this something specific to your fork ?

**Comment by IMXEren** [comment]
Sorry, I forgot about mentioning this. Indeed, it's the patch for reddit_sync that I have implemented. It's just a copy of how you implement newer apps and nothing else.

In my test, invalid characters were included when using a custom version which ultimately used `src/parser.py` build output template to include that custom version in the file name.

You are free to close this PR. I just wanted to let you know about this and not a big deal.

Btw, it was @Spacellary who pointed this out to me.

**Comment by nikhilbadyal** [comment]
Hey, thanks for the PR.
After giving it some thought, I believe it's better to have the fix in code in the main codebase instead of using GitHub Actions. This way, we can use it for other strings in the future if needed. Therefore, I raised [this](https://github.com/nikhilbadyal/docker-py-revanced/pull/216/files)  to fix the issue.

**Pull request closed without merging**
